import { useRef } from 'react'
import Head from 'next/head'
import { About, Contact, Footer, Header, Hero, Work } from '../components/'

const Home = () => {
  const aboutRef = useRef(null)

  return (
    <>
      <Head>
        <title>TDWL.DEV</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Hero ref={aboutRef} />
      <About ref={aboutRef} />
      <Work />
      <Contact />
      <Footer />
    </>
  )
}

export default Home
