import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Flex, Box, Grid, Button } from 'theme-ui'

const Home = () => {
  const [showNav, setShowNav] = useState(false)

  return (
    <>
      <Head>
        <title>TDWL.DEV</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Flex
        sx={{
          fontFamily: 'heading',
          height: '93px',
          p: '1em',
          position: 'fixed',
          top: 0,
          width: '100%',
          backgroundColor: 'white',
          zIndex: '3',
        }}
      >
        <Box sx={{ height: '59px', width: '59px' }}>
          <Image src="/images/logo.png" alt="TDWL.DEV" width="59" height="59" />
        </Box>
        <Flex sx={{ flex: '1 1 auto', justifyContent: 'flex-end' }}>
          <Grid
            width="59px"
            onClick={() => setShowNav(!showNav)}
            sx={{
              cursor: 'pointer',
              div: {
                height: '2px',
                width: showNav ? '59px' : '25px',
              },
            }}
          >
            <Box
              sx={{
                backgroundColor: 'black',
                transition: 'all 300ms ease',
              }}
            />
            <Box
              sx={{
                margin: '0 auto',
                backgroundColor: 'black',
                transition: 'all 400ms ease',
              }}
            />
            <Box
              sx={{
                marginLeft: 'auto',
                backgroundColor: 'black',
                transition: 'all 200ms ease',
              }}
            />
          </Grid>
        </Flex>
      </Flex>
      <Flex
        sx={{
          position: 'relative',
          alignItems: 'center',
          height: 'calc(100vh - 93px)',
          marginTop: '93px',
        }}
      >
        <Box
          sx={{
            fontFamily: 'heading',
            position: 'absolute',
            zIndex: '2',
            color: 'white',
            fontSize: '28px',
            padding: '1em',
          }}
        >
          We develop <b>carefully</b>
          <br />
          <b>crafted</b> websites
          <b>
            <br />
            tailored
          </b>{' '}
          to <b>your</b>
          <br /> business
          <Link href="#work" passHref>
            <Box>
              <Button variant="primary" mt={4}>
                Our Work
              </Button>
            </Box>
          </Link>
        </Box>
        <Box
          sx={{
            fontFamily: 'heading',
            position: 'absolute',
            bottom: '0px',
            zIndex: '2',
            color: 'white',
            fontSize: '24px',
            padding: '1em',
            width: '100%',
            textAlign: 'center',
          }}
        >
          <Link href="#about" passHref>
            <Box
              sx={{
                paddingTop: '40px',
                cursor: 'pointer',
                span: {
                  position: 'absolute',
                  top: '0',
                  left: '50%',
                  width: '24px',
                  height: '24px',
                  marginLeft: '-12px',
                  borderLeft: '1px solid white',
                  borderBottom: '1px solid white',
                  WebkitTransform: 'rotate(-45deg)',
                  transform: 'rotate(-45deg)',
                  WebkitAnimation: 'sdb07 2s infinite',
                  animation: 'sdb07 2s infinite',
                  opacity: 0,
                  boxSizing: 'border-box',
                },
                'span:nth-of-type(1)': {
                  WebkitAnimationDelay: '0s',
                  animationDelay: '0s',
                },
                'span:nth-of-type(2)': {
                  top: '16px',
                  WebkitAnimationDelay: '0.15s',
                  animationDelay: '0.15s',
                },
                'span:nth-of-type(3)': {
                  top: '32px',
                  WebkitAnimationDelay: '0.3s',
                  animationDelay: '0.3s',
                },
                '@-webkit-keyframes sdb07': {
                  '0%': {
                    opacity: '0',
                  },
                  '50%': {
                    opacity: '1',
                  },
                  '100%': {
                    opacity: '0',
                  },
                },
                '@keyframes sdb07': {
                  '0%': {
                    opacity: '0',
                  },
                  '50%': {
                    opacity: '1',
                  },
                  '100%': {
                    opacity: '0',
                  },
                },
              }}
            >
              <span></span>
              <span></span>
              <span></span>
            </Box>
          </Link>
        </Box>
        <Box
          sx={{
            position: 'absolute',
            zIndex: '1',
            backgroundColor: 'black',
            height: 'calc(100vh - 93px)',
            width: '100%',
            opacity: '0.4',
          }}
        />
        <video
          style={{
            position: 'absolute',
            objectFit: 'cover',
            height: 'calc(100vh - 93px)',
            width: '100%',
          }}
          src="/videos/video.mp4"
          autoPlay
          loop
          muted
          playsInline
        />
      </Flex>
      {/* <Box>test</Box> */}
    </>
  )
}

export default Home
